cluster:
  mkdir -p logs/sge/{rule} &&
  qsub 
    -V
    -j yes 
    -N smk-{rule}-{wildcards} 
    -o logs/sge/{rule}/log.out 
    -e logs/sge/{rule}/log.error 
    -pe smp {threads} 
    -l h_stack=128m 
    -l m_mem_free={resources.mem_gb}G
    -l h_rt={resources.time}
default-resources:
  - threads=1
  - mem_gb=4
  - time="01:00:00"
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 100
keep-going: False
rerun-incomplete: True
printshellcmds: True
use-conda: False
use-singularity: True
